version: '3.9'

services:
  mysql:
    image: library/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root-password
      MYSQL_DATABASE: full-stack-ecommerce
      MYSQL_USER: ecommerceapp
      MYSQL_PASSWORD: ecommerceapp
    volumes:
      - mysql-data-volume:/var/lib/mysql:rw
    restart: always
    container_name: springboot-ecommerce-mysql

  springboot-backend:
    build: ./
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - mysql
    restart: always
    container_name: springboot-ecommerce-container

  angular-frontend:
    build: ./src/main/resources/webapp/angular-ecommerce
    ports:
      - "4200:4200"
    depends_on:
      - springboot-backend
    container_name: angular-ecommerce-container

volumes:
  mysql-data-volume: